apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "jenkins", "namespace": "", "kind": "DeploymentConfig"}]'
  labels:
    app: cicd-pipeline
    name: cicd-pipeline
  name: hello-small-pipeline
spec:
  triggers:
  - github:
      secret: SSAs345m6bnU
    type: GitHub
  - generic:
      secret: SSAs345m6bnU
    type: Generic
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
            stage 'build'
            openshiftBuild(buildConfig: 'jenkins', showBuildLogs: 'true')
            stage 'deploy'
            openshiftDeploy(deploymentConfig: 'jenkins')
        }
    type: JenkinsPipeline
